tasks:
    - name: Secrets & configurations
      command: |
        eval $(gp env -e)
        npm i
        
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - k--kato.intellij-idea-keybindings
    - ms-azuretools.vscode-docker
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - redhat.vscode-yaml
    - toba.vsfire