title: Langame
description: Machine conversations for human conversations.
termsOfService: https://help.langa.me/terms
contact:
  name: API Support
  email: louis.beaumont@langa.me
license:
  name: GNU General Public License v3.0
  url: https://www.gnu.org/licenses/gpl-3.0.en.html
version: 0.0.1
