
seo:
  title: Redocly Portal Example
  description: The best API documentation generator ever.
  siteUrl: https://portal-demo.redoc.ly
logo:
  image: ./docs/favicon.png
  altText: Portal logo
toc:
  enable: true
disableLastModified: true
showPrevButton: true
disableImagesOptimization: true
oasDefinitions:
  petstore: ./docs/openapi/petstore.yaml
stylesheets:
  - 'https://fonts.googleapis.com/css?family=Roboto:300,400,600,700'
scripts:
  - ./static/intercom.js
nav:
  - label: Training exercises
    page: developer-portal/index.md
    external: true
  - label: External docs
    icon: ./images/redocly-icon-white.png
    href: 'https://docs.redoc.ly/developer-portal/introduction/'
  - search: true
footer:
  copyrightText: Copyright © Redocly Portal Example
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://redoc.ly/subscription-agreement/'
          external: true
        - label: Privacy Notice
          href: 'https://redoc.ly/privacy-policy/'
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
