
name: Build docs
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: ./build_cd.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,build_cd.sh,docs,.gitpod*,package*,.gitignore'
        cname: docs.langa.me
    - name: Generate Changelog
      run: git log | head > ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
      env:
        GITHUB_REPOSITORY: langa-me/api